<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nur Athifah Ayu Anhar">
<meta name="dcterms.date" content="2023-01-18">

<title>Analisis Pengaruh Ekspor Kopi ke Amerika Serikat Terhadap Pertumbuhan Ekonomi Indonesa Tahun 2010-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Ekspor Kopi ke Amerika Serikat Terhadap Pertumbuhan Ekonomi Indonesa Tahun 2010-2021</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nur Athifah Ayu Anhar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 18, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> 1 Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> 1.2 Latar Belakang</h3>
<p>Kopi merupakan salah satu komoditi yang paling banyak diekspor, oleh karena itu kopi menjadi sektor yang sangat berpengaruh untuk nilai ekspor atau bisa dikatakan sebagai sumber utama devisa negara. Pada tahun 2021 Indonesia masih menjadi eksportir kopi terbesar keempat, di antara Brazil yang menempatkan posisi pertama, Vietnam menjadi posisi kedua, dan posisi ketiga yaitu Kolombia. Amerika Serikat menjadi negara tujuan utama ekspor kopi Indonesia dikarenakan masyarakat Amerika Serikat menyukai kopi Indonesia yang memiliki cita rasa yang khas, memiliki banyak variasi, dan juga memiliki kualitas yang sangat baik. Penelitian ini bertujuan untuk mengetahui pengaruh dari ekspor kopi ke Amerika Serikat terhadap pertumbuhan ekonomi Indonesia.</p>
<p>Menurut data dari Badan Pusat Statistik, pada tahun 2021 Indonesia menyumbang nilai ekspor pada komoditi kopi yaitu sebesar USD 842.500.000 dengan volume 380.200 kg. Sedangkan pada tahun 2020 nilai ekspor pada komoditi kopi sedikit lebih rendah apabila dibandingkan pada tahun 2021 yaitu sebesar USD 809.200.000 dengan volume 375.600 kg. Apabila hanya ekspor kopi ke Amerika Serikat saja, Indonesia telah menyumbang nilai ekspor sebesar USD 194.769,10 di tahun 2021. Sedangkan di tahun 2020 nilai ekspor kopi ke Amerika Serikat lebih tinggi bila dibandingkan dari tahun sebelumnya, yaitu sebesar USD 202.352,00. Dari data tersebut Indonesia mengalami fluktuasi. Hal ini terjadi karena adanya beberapa faktor salah satunya yaitu adanya virus COVID-19 yang menyebabkan nilai kurs, harga kopi, dan PDB Amerika Serikat serta Indonesia mengalami perubahan.</p>
</section>
<section id="batasan-masalah" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="batasan-masalah"><span class="header-section-number">1.2</span> 1.3 Batasan Masalah</h3>
<p>Pembatasan suatu masalah digunakan untuk membatasi jangkauan proses yang akan dibahas agar tetap pada satu topik dan menghindari pelebaran pokok permasalahan. Peneliti menetapkan batasan masalah atas beberapa hal, yaitu membahas terkait nilai ekspor kopi ke Amerika Serikat, pertumbuhan, dan Produk Domestik Bruto Indonesia.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> 1.4 Rumusan masalah</h3>
<ol type="1">
<li>Bagaimana pengaruh ekspor kopi ke Amerika Serikat secara simultan terhadap pertumbuhan ekonomi Indonesia tahun 2010-2021?</li>
<li>Bagaimana pengaruh ekspor kopi ke Amerika Serikat secara parsial terhadap pertumbuhan ekonomi Indonesia tahun 2010-2021?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> 1.5 Tujuan dan manfaat penelitian</h3>
<ol type="1">
<li>Untuk mengetahui pengaruh ekspor kopi ke Amerika Serikat secara simultan terhadap pertumbuhan ekonomi Indonesia dari tahun ke tahun.</li>
<li>Untuk mengetahui pengaruh ekspor kopi ke Amerika Serikat secara parsial terhadap pertumbuhan ekonomi Indonesia dari tahun ke tahun.</li>
</ol>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> 2 Studi pustaka</h2>
<section id="perdagangan-internasional" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="perdagangan-internasional"><span class="header-section-number">2.1</span> 2.1 Perdagangan Internasional</h3>
<p>Secara umum perdagangan internasional merupakan sarana untuk melakukan pertukaran barang dan jasa internasional. Dalam lima puluh tahun terakhir, perdagangan internasional telah tumbuh dan berkembang secara drastis dan dalam ukuran yang besar. Hal ini disebabkan oleh adanya kerjasama yang dilakukan oleh berbagai negara untuk menghilangkan proteksi perdagangan dan adanya keinginan untuk mempromosikan perdagangan barang dan jasa secara bebas. Menurut pandangan Basri dan Munandar, perdagangan internasional merupakan perdagangan yang terjadi karena ada negara yang memiliki sebuah sumber daya yang berbeda dengan negara yang diajak kerja sama. Menurut Basri dan Munandar, perdagangan internasional ini dapat terjadi karena adanya aktivitas produksi barang dalam jumlah yang cukup besar.</p>
</section>
<section id="produk-domestik-bruto" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="produk-domestik-bruto"><span class="header-section-number">2.2</span> 2.2 Produk Domestik Bruto</h3>
<p>Produk Domestik Bruto (PDB) adalah pendapatan total dan pengeluaran total nasional atas output barang dan jasa pada periode tertentu. PDB ini dapat mencerminkan kinerja ekonomi, sehingga semakin tinggi PDB suatu negara maka dapat dikatakan bahwa semakin bagus pula kinerja ekonomi di negara tersebut. Menurut Sukirno (2013:34) dalam bukunya makroekonomi teori pengantar, Produk Domestik Bruto (PDB) dapat diartikan sebagai nilai barang-barang dan jasa-jasa yang diproduksikan di dalam negara dalam satu tahun tertentu.</p>
<section id="ekspor" class="level4" data-number="2.2.1">
<h4 data-number="2.2.1" class="anchored" data-anchor-id="ekspor"><span class="header-section-number">2.2.1</span> 2.3 Ekspor</h4>
<p>Menurut Amir M.S. (2009;1) , Ekspor adalah mengeluarkan barang dari peredaran dalam masyarakat dan mengirimkan ke luar negeri sesuai ketentuan pemerintah dan mengharapkan pembayaran dalam valuta asing.</p>
</section>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> 3 Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> 3.1 Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>PDB Indonesia (USD)</th>
<th>Nilai Ekspor (000$)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2010</td>
<td>755094160363.07</td>
<td>176360.60</td>
</tr>
<tr class="even">
<td>2011</td>
<td>892969107923.09</td>
<td>274491</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>917869910105.75</td>
<td>330814.70</td>
</tr>
<tr class="even">
<td>2013</td>
<td>912524136718.02</td>
<td>207037.60</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>890814755233.23</td>
<td>295903.10</td>
</tr>
<tr class="even">
<td>2015</td>
<td>860854235065.08</td>
<td>281079.10</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>931877364177.74</td>
<td>269895.60</td>
</tr>
<tr class="even">
<td>2017</td>
<td>1015618742565.81</td>
<td>256351.40</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>1042271531011.99</td>
<td>254030.70</td>
</tr>
<tr class="even">
<td>2019</td>
<td>1119099868265.25</td>
<td>253830.10</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>1058688935454.78</td>
<td>202352.00</td>
</tr>
<tr class="even">
<td>2021</td>
<td>1186092991320.04</td>
<td>194769.10</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.0 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'uasmetopel.xlsx'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>X, <span class="at">y=</span>Y))<span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">'purple'</span>, <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Tabel 1. Hubungan Antara Ekspor Kopi ke US dan PDB Indonesia"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"PBD Indonesia"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Nilai Ekspor Kopi"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Sumber: World Development Indicators, Badan Pusat Statistik"</span>) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mpg" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/fig-mpg-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Hubungan Antara Nilai Ekspor Kopi ke US dan PDB Indonesia</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> 3.2 Metode analisis</h3>
<p>Teknik analisis yang digunakan dalam penelitian ini adalah teknik kuantitatif dan penjabaran deskriptif. Teknik analisis kuantitatif yang dilakukan dalam penelitian ini dengan melakukan regresi univariat atau Ordinary Least Square (OLS) menggunakan R sebagai alat bantu pengolahan data dengan satu variabel independen. Package yang digunakan adalah library(tidyverse), library(readxl), library (WDI), library(ggplot). Penelitian ini bertujuan untuk mengetahui pengaruh ekspor kopi ke Amerika Serikat terhadap pertumbuhan ekonomi Indonesia dari tahun ke tahun. Rumus yang digunakan untuk regresi, sebagai berikut:</p>
<p><span class="math display">\[
x_{t}=\beta_0 + \beta_1 y_t+\mu_t
\]</span></p>
<p>Di mana <span class="math inline">\(x_t\)</span> adalah PDB Indonesia dan <span class="math inline">\(y_t\)</span> adalah Nilai Ekspor Kopi ke Amerika Serikat.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> 4 Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> 4.1 Pembahasan masalah</h3>
<ol type="1">
<li>Nilai Ekspor Kopi ke Amerika Serikat</li>
</ol>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Tahun</th>
<th style="text-align: center;">Nilai Ekspor ($)</th>
<th style="text-align: center;">Pertumbuhan (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2010</td>
<td style="text-align: center;">176360600.00</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: center;">2011</td>
<td style="text-align: center;">274491000.00</td>
<td style="text-align: center;">56</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2012</td>
<td style="text-align: center;">330814700.00</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="even">
<td style="text-align: center;">2013</td>
<td style="text-align: center;">207037600.00</td>
<td style="text-align: center;">-37</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2014</td>
<td style="text-align: center;">295903100.00</td>
<td style="text-align: center;">43</td>
</tr>
<tr class="even">
<td style="text-align: center;">2015</td>
<td style="text-align: center;">281079100.00</td>
<td style="text-align: center;">-5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2016</td>
<td style="text-align: center;">269895600.00</td>
<td style="text-align: center;">-4</td>
</tr>
<tr class="even">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">256351400.00</td>
<td style="text-align: center;">-5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">254030700.00</td>
<td style="text-align: center;">-1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">253830100.00</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">202352000.00</td>
<td style="text-align: center;">-20</td>
</tr>
<tr class="even">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">194769100.00</td>
<td style="text-align: center;">-4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Rata-rata</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">38</td>
</tr>
</tbody>
</table>
<p>Sumber: Badan Pusat Statistik (data diolah)</p>
<p>Berdasarkan tabel diatas ditunjukkan bahwa dari tahun 2010-2021 nilai ekspor kopi Indonesia ke Amerika dinyatakan fluktuasi atau naik turun setiap tahunnya. Dari tahun 2010 ke tahun 2011 nilai ekspor kopi Indonesia ke Amerika tercatat meningkat dengan perkembangan 56%. Namun, dari tahun 2012 ke tahun 2013 mengalami penurunan sebesar 37%. Di tahun 2014 nilai ekspor kopi kembali naik di angka 43%, namun mengalami penurunan selama 2015 hingga 2021 secara terus meneru. Puncaknya adalah di tahun 2020 yang mengalami penurunan sebesar 20% hal tersebut dikarenakan pandemi COVID-19.</p>
<ol start="2" type="1">
<li>Produk Domestik Bruto Indonesia</li>
</ol>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Tahun</th>
<th style="text-align: center;">PDB Indonesia ($)</th>
<th style="text-align: center;">Pertumbuhan (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2010</td>
<td style="text-align: center;">755094160363.07</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: center;">2011</td>
<td style="text-align: center;">892969107923.09</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2012</td>
<td style="text-align: center;">917869910105.75</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">2013</td>
<td style="text-align: center;">912524136718.02</td>
<td style="text-align: center;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2014</td>
<td style="text-align: center;">890814755233.23</td>
<td style="text-align: center;">-2</td>
</tr>
<tr class="even">
<td style="text-align: center;">2015</td>
<td style="text-align: center;">860854235065.08</td>
<td style="text-align: center;">-3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2016</td>
<td style="text-align: center;">931877364177.74</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">1015618742565.81</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">1042271531011.99</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">1119099868265.25</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">1058688935454.78</td>
<td style="text-align: center;">-5</td>
</tr>
<tr class="even">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">1186092991320.04</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Rata-rata</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">4,4</td>
</tr>
</tbody>
</table>
<p>Sumber: World Development Indicators (data diolah)</p>
<p>Berdasarkan tabel di atas, pertumbuhan PDB Indonesia tahun 2010-2021 tumbuh secara fluktuatif. Pada tahun 2010-2011 PDB Indonesia mengalami perkembangan sebesar 18%. Pertumbuhan ekonomi pada tahun tersebut perkembang baik, pendapatan masyarakat dapat menopang konsumsi masyarakat dan tumbuh stabil. Pada tahun-tahun berikutnya sampai pada tahun 2015 PDB Indonesia terus mengalami penurunan sampai di tahun terendahnya yaitu 2015 yaitu sebesar -3% sejumlah USD 860.854.235.065. Pada 2 tahun berikutnya tahun 2016-2017 PDB Indonesia mengalami pertumbuhan sebesar 8% kenaikan ini disebabkan struktur ekonomi Indonesia secara spasial tahun 2017 didominasi oleh kelompok provinsi di Pulau Jawa dan Pulau Sumatera. Kelompok provinsi di Pulau Jawa memberikan kontribusi terbesar terhadap Produk Domestik Bruto, yakni sebesar 58,49 persen, diikuti oleh Pulau Sumatera sebesar 21,66 persen, dan Pulau Kalimantan 8,20 persen. Selanjutnya di tahun 2020 PDB Indonesia mengalami penurunan kembali sebesar -5% dan mengalami kenaikan kembali di tahun berikutnya yaitu sebesar 12%</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> 4.2 Analisis masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variabel</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>1.079e+12</td>
<td>2.082e+11</td>
<td>5.184</td>
<td>0.000411 ***</td>
</tr>
<tr class="even">
<td>Y</td>
<td>-4.563e+02</td>
<td>8.210e+02</td>
<td>-0.556</td>
<td>0.590561</td>
</tr>
</tbody>
</table>
<table class="table">
<thead>
<tr class="header">
<th>Multiple R-squared</th>
<th>0.02997</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adjusted R-squared</td>
<td>-0.06704</td>
</tr>
<tr class="even">
<td>F-statistic</td>
<td>0.3089</td>
</tr>
<tr class="odd">
<td>p-value</td>
<td>0.5906</td>
</tr>
</tbody>
</table>
<p>Uji simultan (Uji F) dilakukan untuk menguji seberapa besar pengaruh dari variabel independen yaitu volume ekspor kopi terhadap variabel dependen. Berdasarkan hasil regresi diperoleh nilai F-statistic sebesar 0.3089 dengan probabilitas 0.5906 (&gt; α=0,1). Sehingga variabel volume ekspor kopi ke Amerika Serikat tidak berpengaruh signifikan terhadap pertumbuhan ekonomi Indonesia selama periode 2010-2021.</p>
<p>Nilai R² digunakan untuk menunjukkan seberapa besar pengaruh variabel independen terhadap variabel dependen. Berdasarkan pada tabel di atas, hasil nilai R² menunjukkan bahwa pertumbuhan ekonomi Indonesia dipengaruhi oleh variabel volume ekspor kopi ke Amerika Serikat sebesar 0.02997 atau 2.997%. Artinya hanya 2.997% perkembangan ekonomi Indonesia dipengaruhi oleh volume ekspor kopi ke Amerika Serikat. Sedangkan sebanyak 97,003% dipengaruhi oleh variabel lain yang tidak termasuk dalam penelitian ini.</p>
<p>Dari hasil perhitungan di atas, pada variabel Y atau nilai ekspor kopi ke Amerika Serikat didapatkan t-value -0.556 dengan probabilitas 0.590561 &gt; α=0,1. Maka dari itu dapat dikatakan bahwa secara parsial nilai ekspor kopi ke Amerika Serikat tidak berpengaruh secara signifikan terhadap pertumbuhan ekonomi Indonesia pada periode 2010-2021.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>uasmetopel<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"uasmetopel.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(X<span class="sc">~</span>Y,<span class="at">data=</span>uasmetopel)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = X ~ Y, data = uasmetopel)

Residuals:
       Min         1Q     Median         3Q        Max 
-2.437e+11 -6.386e+10 -1.735e+10  7.354e+10  1.957e+11 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.079e+12  2.082e+11   5.184 0.000411 ***
Y           -4.563e+02  8.210e+02  -0.556 0.590561    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.252e+11 on 10 degrees of freedom
Multiple R-squared:  0.02997,   Adjusted R-squared:  -0.06704 
F-statistic: 0.3089 on 1 and 10 DF,  p-value: 0.5906</code></pre>
</div>
</div>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> 5 Kesimpulan</h2>
<p>Berdasarkan data penelitian di atas membuktikan bahwa ekpor kopi ke Amerika Serikat tidak berpengaruh secara signifikan terhadap pertumbuhan ekonomi Indonesia. Dengan variabel independen yaitu nilai ekspor kopi ke Amerika Serikat yang menjadi faktor yang dapat mendorong naik dan turunnya variabel dependen yaitu PDB Indonesia. Nilai ekspor kopi Indonesia ke Amerika Serikat hanya menyumbang sekitar 3% dari total Produk Domestik Bruto Indonesa pada tahun 2010-2021. Sedangkan 97% lainnya dipengaruhi oleh variabel lain.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> 6 Referensi</h2>
<p>Badan Pusat Statistik. (n.d.). Retrieved January 20, 2023, from https://www.bps.go.id/statictable/2014/09/08/1014/ekspor-kopi-menurut-negara-tujuan-utama-2000-2021.html</p>
<p>GDP (current US$)—Indonesia | Data 2010-2021 (2022). Retrieved January 20, 2023, from https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?locations=ID</p>
<p>Fadila, F. (2022). Pengertian dan Teori Perdagangan Internasional Menurut Para Ahli. Gramedia Literasi. https://www.gramedia.com/literasi/pengertian-dan-teori-perdagangan-internasional/</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>